c_stdlib_version:              # [linux]
  - 2.17                       # [linux]

c_stdlib_version:                                   # [linux64]
  - 2.17                                            # [linux64]
  - 2.17                                            # [linux64]
  - 2.17                                            # [linux64]
  - 2.28                                            # [linux64]
docker_image:                                       # [linux64]
  - quay.io/condaforge/linux-anvil-cos7-x86_64      # [linux64]
  - quay.io/condaforge/linux-anvil-cuda:11.8        # [linux64]
  - quay.io/condaforge/linux-anvil-cos7-x86_64      # [linux64]
  - quay.io/condaforge/linux-anvil-alma-x86_64:8    # [linux64]
# rest just to make smithy happy
c_compiler_version:                                 # [linux64]
  - 13                                              # [linux64]
  - 11                                              # [linux64]
  - 12                                              # [linux64]
  - 12                                              # [linux64]
cxx_compiler_version:                               # [linux64]
  - 13                                              # [linux64]
  - 11                                              # [linux64]
  - 12                                              # [linux64]
  - 12                                              # [linux64]
fortran_compiler_version:                           # [linux64]
  - 13                                              # [linux64]
  - 11                                              # [linux64]
  - 12                                              # [linux64]
  - 12                                              # [linux64]
cdt_name:                                           # [linux64]
  - cos7                                            # [linux64]
  - cos7                                            # [linux64]
  - cos7                                            # [linux64]
  - cos7                                            # [linux64]
cuda_compiler:                                      # [linux64]
  - None                                            # [linux64]
  - nvcc                                            # [linux64]
  - cuda-nvcc                                       # [linux64]
  - cuda-nvcc                                       # [linux64]
cuda_compiler_version:                              # [linux64]
  - None                                            # [linux64]
  - 11.8                                            # [linux64]
  - 12.0                                            # [linux64]
  - 12.6                                            # [linux64]
